# Site
title:              "Oscar Johnson"
bio:                'My Portfolio'
description:        "An up to date portfolio of my work so far"
reading_time:       true
words_per_minute:   200
logo:               'https://scontent-lht6-1.xx.fbcdn.net/v/t1.0-1/p160x160/17022349_1563370107026484_2031413660904259523_n.jpg?oh=75176271cc0992458418a0ecf125c251&oe=5A3E3807'
background:         'http://www.wallpapermade.com/images/wallpapers/originals/the-witcher-3-wild-hunt-beautiful-landscape-wallpaper-4461.jpg'
tiled_bg:           true   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://johnnersuk.github.io
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed
#Fixed updates
timezone:           Europe/London
future:             true


# Comments
disqus_shortname:   Johnners

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:               oscarjohnson.acs@gmail.com
#twitter:            huxyuk
#facebook:           username
#github-url:         huxyuk
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:           huxyuk
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
